apiVersion: v1
kind: PersistentVolume
metadata:
  name: sinusbot-data
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /data/nfsshare/sinusbot-data 
    server: 192.168.50.16
  persistentVolumeReclaimPolicy: Retain
